# Generated by Django 4.2.13 on 2024-05-28 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preprocessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaned_text', models.TextField(blank=True, null=True)),
                ('case_folded_text', models.TextField(blank=True, null=True)),
                ('normalized_text', models.TextField(blank=True, null=True)),
                ('tokenized_text', models.TextField(blank=True, null=True)),
                ('stopwords_removed_text', models.TextField(blank=True, null=True)),
                ('stemmed_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataset.dataset')),
            ],
        ),
    ]
