# Generated by Django 4.2.13 on 2024-06-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metode', models.CharField(max_length=255)),
                ('test_size', models.FloatField()),
                ('train_size', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('csv_path', models.CharField(max_length=255)),
                ('confusion_matrix_path', models.CharField(max_length=255)),
                ('model_path', models.CharField(max_length=255)),
                ('vectorizer_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
