# Generated by Django 4.2.13 on 2024-06-13 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_testfeatures_trainfeatures'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestFeatures',
        ),
        migrations.DeleteModel(
            name='TrainFeatures',
        ),
    ]
